# -*- coding: utf-8 -*-

country_codes = [
	'FI',
	'ME',
	'GB',
	'LI',
	'ES',
	'AD',
	'CZ',
	'EE',
	'MD',
	'TN',
	'LU',
	'MC',
	'SE',
	'AM',
	'SI',
	'CY',
	'HU',
	'RS',
	'AZ',
	'IE',
	'RU',
	'PL',
	'PT',
	'XK',
	'SK',
	'UZ',
	'EG',
	'VA',
	'IS',
	'MK',
	'DK',
	'RO',
	'NO',
	'IL',
	'NL',
	'IT',
	'LT',
	'MN',
	'LV',
	'GE',
	'AT',
	'CH',
	'FR',
	'GR',
	'BG',
	'BE',
	'DE',
	'KX',
	'HR',
	'TR',
	'UA'
]

country_names_dict = {'FI': 'Финляндия', 'ME': 'Черногория', 'GB': 'Великобритания', 'LI': 'Лихтенштейн', 'ES': 'Испания', 'AD': 'Андорра', 'CZ': 'Чехия', 'EE': 'Эстония', 'MD': 'Молдавия', 'TN': 'Тунис', 'LU': 'Люксембург', 'MC': 'Монако', 'SE': 'Швеция', 'AM': 'Армения', 'SI': 'Словения', 'CY': 'Кипр', 'HU': 'Венгрия', 'RS': 'Сербия', 'AZ': 'Азербайджан', 'IE': 'Ирландия', 'RU': 'Россия', 'PL': 'Польша', 'PT': 'Португалия', 'XK': 'Косово', 'SK': 'Словакия', 'UZ': 'Узбекистан', 'EG': 'Египет', 'VA': 'Ватикан', 'IS': 'Исландия', 'MK': 'Македония', 'DK': 'Дания', 'RO': 'Румыния', 'NO': 'Норвегия', 'IL': 'Израиль', 'NL': 'Нидерланды', 'IT': 'Италия', 'LT': 'Литва', 'MN': 'Монголия', 'LV': 'Латвия', 'GE': 'Грузия', 'AT': 'Австрия', 'CH': 'Швейцария', 'FR': 'Франция', 'GR': 'Греция', 'BG': 'Болгария', 'BE': 'Бельгия', 'DE': 'Германия', 'KX': 'Крым', 'HR': 'Хорватия', 'TR': 'Турция', 'UA': 'Украина'}

countries = [
	{		
		"name":"Финляндия",
		"currency":"EUR",
		"code":"FI",
		"cases":{
			"vi":"в Финляндию",
			"tv":"Финляндией",
			"ro":"Финляндии",
			"pr":"Финляндии",
			"da":"Финляндии"
	},
		"name_translations":{
			"en":"Finland"
		}},
	{
		"name":"Черногория",
		"currency":"EUR",
		"code":"ME",
		"cases":{
			"vi":"в Черногорию",
			"tv":"Черногорией",
			"ro":"Черногории",
			"pr":"Черногории",
			"da":"Черногории"
	},
		"name_translations":{
				"en":"Montenegro"
			}
	},
	{
		"name":"Великобритания",
		"currency":"GBP",
		"code":"GB",
		"cases":{
			"vi":"в Великобританию",
			"tv":"Великобританией",
			"ro":"Великобритании",
			"pr":"Великобритании",
			"da":"Великобритании"
	},
		"name_translations":{
				"en":"United Kingdom"}
			},
	{
		"name":"Лихтенштейн",
		"currency":"CHF",
		"code":"LI",
		"cases":{
			"vi":"в Лихтенштейн",
			"tv":"Лихтенштейном",
			"ro":"Лихтенштейн",
			"pr":"о Лихтенштейне",
			"da": "Лихтенштейну"
		},
		"name_translations":{
			"en":"Liechtenstein"
		}
	},
	{
		"name":"Испания",
		"currency":"EUR",
		"code":"ES",
		"cases":{
			"vi":"в Испанию",
			"tv":"Испанией",
			"ro":"Испании",
			"pr":"Испании",
			"da":"Испании"
		},
		"name_translations":{
			"en":"Spain"
		}
	},
	{
		"name":"Андорра",
		"currency":"EUR",
		"code":"AD",
		"cases":{
			"vi":"в Андорру",
			"tv":"Андоррой",
			"ro":"Андорры",
			"pr":"Андорре",
			"da":"Андорре"
	},
		"name_translations":{
				"en":"Andorra"
			}
	},
	{
		"name":"Чехия",
		"currency":"CZK",
		"code":"CZ",
		"cases":{
			"vi":"в Чехию",
			"tv":"Чехией",
			"ro":"Чехии",
			"pr":"Чехии",
			"da":"Чехии"
		},
		"name_translations":{
				"en":"Czech Republic"
		}
	},
	{
		"name":"Эстония",
		"currency":"EUR",
		"code":"EE",
		"cases":{
			"vi":"в Эстонию",
			"tv":"Эстонией",
			"ro":"Эстонии",
			"pr":"Эстонии",
			"da":"Эстонии"
		},
		"name_translations":{
			"en":"Estonia"
		}
	},
	{
		"name":"Молдавия",
		"currency":"MDL",
		"code":"MD",
		"cases":{
			"vi":"в Молдову",
			"tv":"Молдовой",
			"ro":"Молдовы",
			"pr":"Молдове",
			"da":"Молдове"
	},
		"name_translations":{
				"en":"Moldova"
			}
	},
	{
		"name":"Тунис",
		"currency":"TND",
		"code":"TN",
		"cases":{
			"vi":"в Тунис",
			"tv":"Тунисом",
			"ro":"Туниса",
			"pr":"Тунисе",
			"da":"Тунису"
	},
		"name_translations":{
				"en":"Tunisia"
			}
	},
	{
		"name":"Люксембург",
		"currency":"EUR",
		"code":"LU",
		"cases":{
			"vi":"в Люксембург",
			"tv":"Люксембургом",
			"ro":"Люксембурга",
			"pr":"Люксембурге",
			"da":"Люксембургу"
	},
		"name_translations":{
				"en":"Luxembourg"
			}
	},
	{
		"name":"Монако",
		"currency":"EUR",
		"code":"MC",
		"cases":{
			"vi":"в Монако",
			"tv":"Монако",
			"ro":"Монако",
			"pr":"Монако",
			"da":"Монако"
	},
		"name_translations":{
				"en":"Monaco"
			}
	},
	{
		"name":"Швеция",
		"currency":"SEK",
		"code":"SE",
		"cases":{
			"vi":"в Швецию",
			"tv":"Швецией",
			"ro":"Швеции",
			"pr":"Швеции",
			"da":"Швеции"
	},
		"name_translations":{
				"en":"Sweden"
			}
	},
	{
		"name":"Армения",
		"currency":"AMD",
		"code":"AM",
		"cases":{
			"vi":"в Армению",
			"tv":"Арменией",
			"ro":"Армении",
			"pr":"Армении",
			"da":"Армении"
	},
		"name_translations":{
				"en":"Armenia"
			}
	},
	{
		"name":"Словения",
		"currency":"EUR",
		"code":"SI",
		"cases":{
			"vi":"в Словению",
			"tv":"Словенией",
			"ro":"Словении",
			"pr":"Словении",
			"da":"Словении"
	},
		"name_translations":{
				"en":"Slovenia"
			}
	},
	{
		"name":"Кипр",
		"currency":"EUR",
		"code":"CY",
		"cases":{
			"vi":"на Кипр",
			"tv":"Кипром",
			"ro":"Кипра",
			"pr":"Кипре",
			"da":"Кипру"
	},
		"name_translations":{
				"en":"Cyprus"
			}
	},
	{
		"name":"Венгрия",
		"currency":"HUF",
		"code":"HU",
		"cases":{
			"vi":"в Венгрию",
			"tv":"Венгрией",
			"ro":"Венгрии",
			"pr":"Венгрии",
			"da":"Венгрии"
	},
		"name_translations":{
				"en":"Hungary"
			}
	},
	{
		"name":"Сербия",
		"currency":"RSD",
		"code":"RS",
		"cases":{
			"vi":"в Сербию",
			"tv":"Сербией",
			"ro":"Сербии",
			"pr":"Сербии",
			"da":"Сербии"
	},
		"name_translations":{
				"en":"Serbia"
			}
	},
	{
		"name":"Азербайджан",
		"currency":"AZN",
		"code":"AZ",
		"cases":{
			"vi":"в Азербайджан",
			"tv":"Азербайджаном",
			"ro":"Азербайджана",
			"pr":"Азербайджане",
			"da":"Азербайджану"
	},
		"name_translations":{
				"en":"Azerbaijan"
			}
	},
	{
		"name":"Ирландия",
		"currency":"EUR",
		"code":"IE",
		"cases":{
			"vi":"в Ирландию",
			"tv":"Ирландией",
			"ro":"Ирландии",
			"pr":"Ирландии",
			"da":"Ирландии"
	},
		"name_translations":{
				"en":"Ireland"
			}
	},
	{
		"name":"Россия",
		"currency":"RUB",
		"code":"RU",
		"cases":{
			"vi":"в Россию",
			"tv":"Россией",
			"ro":"России",
			"pr":"России",
			"da":"России"
	},
		"name_translations":{
				"en":"Russia"
			}
	},
	{
		"name":"Польша",
		"currency":"PLN",
		"code":"PL",
		"cases":{
			"vi":"в Польшу",
			"tv":"Польшей",
			"ro":"Польши",
			"pr":"Польше",
			"da":"Польше"
	},
		"name_translations":{
				"en":"Poland"
			}
	},
	{
		"name":"Португалия",
		"currency":"EUR",
		"code":"PT",
		"cases":{
			"vi":"в Португалию",
			"tv":"Португалией",
			"ro":"Португалии",
			"pr":"Португалии",
			"da":"Португалии"
	},
		"name_translations":{
				"en":"Portugal"
			}
	},
	{
		"name":"Косово",
		"currency":"EUR",
		"code":"XK",
		"cases":{
			"vi":"Косово","tv":
			"Косово","ro":
			"Косово","pr":
			"Косово","da":
			"Косово"
		},
		"name_translations":{
			"en":"Kosovo"
		}
	},
	{
		"name":"Словакия",
		"currency":"EUR",
		"code":"SK",
		"cases":{
			"vi":"в Словакию",
			"tv":"Словакией",
			"ro":"Словакии",
			"pr":"Словакии",
			"da":"Словакии"
		},
		"name_transltions":{
			"en":"Slovakia"
		}
	},
	{
		"name":"Узбекистан",
		"currency":"UZS",
		"code":"UZ",
		"cases":{
			"vi":"в Узбекистан",
			"tv":"Узбекистаном",
			"ro":"Узбекистана",
			"pr":"Узбекистане",
			"da":"Узбекистану"
		},
		"name_translations":{
				"en":"Uzbekistan"
			}
	},
	{
		"name":"Египет",
		"currency":"EGP",
		"code":"EG",
		"cases":{
			"vi":"в Египет",
			"tv":"Египтом",
			"ro":"Египта",
			"pr":"Египте",
			"da":"Египту"
	},
		"name_translations":{
				"en":"Egypt"
			}
	},
	{
		"name":"Ватикан",
		"currency":"EUR",
		"code":"VA",
		"cases":{
			"vi":"в Ватикан",
			"tv":"Ватиканом",
			"ro":"Ватикана",
			"pr":"о Ватикане",
			"da":"Ватикану"
		},
		"name_translations":{
			"en":"Vatican City"
		}
	},
	{
		"name":"Исландия",
		"currency":"ISK",
		"code":"IS",
		"cases":{
			"vi":"в Исландию",
			"tv":"Исландией",
			"ro":"Исландии",
			"pr":"Исландии",
			"da":"Исландии"
		},
		"name_translations":{
			"en":"Iceland"
			}},
	
	{
		"name":"Македония",
		"currency":"MKD",
		"code":"MK",
		"cases":{
			"vi":"в Македонию",
			"tv":"Македонией",
			"ro":"Македонии",
			"pr":"Македонии",
			"da":"Македонии"
	},
		"name_translations":{
				"en":"Macedonia"
			}
	},
	{
		"name":"Дания",
		"currency":"DKK",
		"code":"DK",
		"cases":{
			"vi":"в Данию",
			"tv":"Данией",
			"ro":"Дании",
			"pr":"Дании",
			"da":"Дании"
	},
		"name_translations":{
				"en":"Denmark"
			}
	},
	{
		"name":"Румыния",
		"currency":"RON",
		"code":"RO",
		"cases":{
			"vi":"в Румынию",
			"tv":"Румынией",
			"ro":"Румынии",
			"pr":"Румынии",
			"da":"Румынии"
	},
		"name_translations":{
				"en":"Romania"
			}
	},
	{
		"name":"Норвегия",
		"currency":"NOK",
		"code":"NO",
		"cases":{
			"vi":"в Норвегию",
			"tv":"Норвегией",
			"ro":"Норвегии",
			"pr":"Норвегии",
			"da":"Норвегии"
	},
		"name_translations":{
				"en":"Norway"
			}
	},
	{
		"name":"Израиль",
		"currency":"ILS",
		"code":"IL",
		"cases":{
			"vi":"в Израиль",
			"tv":"Израилем",
			"ro":"Израиля",
			"pr":"Израиле",
			"da":"Израилю"
	},
		"name_translations":{
				"en":"Israel"
			}
	},
	{
		"name":"Нидерланды",
		"currency":"EUR",
		"code":"NL",
		"cases":{
			"vi":"в Нидерланды",
			"tv":"Нидерландами",
			"ro":"Нидерландов",
			"pr":"Нидерландах",
			"da":"Нидерландам"
	},
		"name_translations":{
				"en":"Netherlands"
			}
	},
	{
		"name":"Италия",
		"currency":"EUR",
		"code":"IT",
		"cases":{
			"vi":"в Италию",
			"tv":"Италией",
			"ro":"Италии",
			"pr":"Италии",
			"da":"Италии"
	},
		"name_translations":{
				"en":"Italy"
			}
	},
	{
		"name":"Литва",
		"currency":"LTL",
		"code":"LT",
		"cases":{
			"vi":"в Литву",
			"tv":"Литвой",
			"ro":"Литвы",
			"pr":"Литве",
			"da":"Литве"
	},
		"name_translations":{
				"en":"Lithuania"
			}
	},
	{
		"name":"Монголия",
		"currency":"MNT",
		"code":"MN",
		"cases":{
			"vi":"в Монголию",
			"tv":"Монголией",
			"ro":"Монголии",
			"pr":"Монголии",
			"da":"Монголии"
	},
		"name_translations":{
				"en":"Mongolia"
			}
	},
	{
		"name":"Латвия",
		"currency":"LVL",
		"code":"LV",
		"cases":{
			"vi":"в Латвию",
			"tv":"Латвией",
			"ro":"Латвии",
			"pr":"Латвии",
			"da":"Латвии"
	},
		"name_translations":{
				"en":"Latvia"
			}
	},
	{
		"name":"Грузия",
		"currency":"GEL",
		"code":"GE",
		"cases":{
			"vi":"в Грузию",
			"tv":"Грузией",
			"ro":"Грузии",
			"pr":"Грузии",
			"da":"Грузии"
	},
		"name_translations":{
				"en":"Georgia"
			}
	},
	{
		"name":"Австрия",
		"currency":"EUR",
		"code":"AT",
		"cases":{
			"vi":"в Австрию",
			"tv":"Австрией",
			"ro":"Австрии",
			"pr":"Австрии",
			"da":"Австрии"
	},
		"name_translations":{
				"en":"Austria"
			}
	},
	{
		"name":"Швейцария",
		"currency":"CHF",
		"code":"CH",
		"cases":{
			"vi":"в Швейцарию",
			"tv":"Швейцарией",
			"ro":"Швейцарии",
			"pr":"Швейцарии",
			"da":"Швейцарии"
	},
		"name_translations":{
				"en":"Switzerland"
			}
	},
	{
		"name":"Франция",
		"currency":"EUR",
		"code":"FR",
		"cases":{
			"vi":"во Францию",
			"tv":"Францией",
			"ro":"Франции",
			"pr":"Франции",
			"da":"Франции"
	},
		"name_translations":{
				"en":"France"
			}
	},
	{
		"name":"Греция",
		"currency":"EUR",
		"code":"GR",
		"cases":{
			"vi":"в Грецию",
			"tv":"Грецией",
			"ro":"Греции",
			"pr":"Греции",
			"da":"Греции"
	},
		"name_translations":{
				"en":"Greece"
			}
	},
	{
		"name":"Болгария",
		"currency":"BGN",
		"code":"BG",
		"cases":{
			"vi":"в Болгарию",
			"tv":"Болгарией",
			"ro":"Болгарии",
			"pr":"Болгарии",
			"da":"Болгарии"
	},
		"name_translations":{
				"en":"Bulgaria"
			}
	},
	{
		"name":"Бельгия",
		"currency":"EUR",
		"code":"BE",
		"cases":{
			"vi":"в Бельгию",
			"tv":"Бельгией",
			"ro":"Бельгии",
			"pr":"Бельгии",
			"da":"Бельгии"
	},
		"name_translations":{
				"en":"Belgium"
			}
	},
	{
		"name":"Германия",
		"currency":"EUR",
		"code":"DE",
		"cases":{
			"vi":"в Германию",
			"tv":"Германией",
			"ro":"Германии",
			"pr":"Германии",
			"da":"Германии"
	},
		"name_translations":{
				"en":"Germany"
			}
	},
	{
		"name":"Крым",
		"currency":"RUB",
		"code":"KX",
		"cases":{
			"vi":"в Крым",
			"tv":"Крымом",
			"ro":"Крыма",
			"pr":"Крыме",
			"da":"Крыму"
		},
		"name_translations":{
				"en":"Crimea"
			}
	},
	{
		"name":"Хорватия",
		"currency":"HRK",
		"code":"HR",
		"cases":{
			"vi":"в Хорватию",
			"tv":"Хорватией",
			"ro":"Хорватии",
			"pr":"Хорватии",
			"da":"Хорватии"
		},
		"name_translations":{
				"en":"Croatia"
			}
	},
	{
		"name":"Турция",
		"currency":"TRY",
		"code":"TR",
		"cases":{
			"vi":"в Турцию",
			"tv":"Турцией",
			"ro":"Турции",
			"pr":"Турции",
			"da":"Турции"
		},
		"name_translations":{
				"en":"Turkey"
			}
	},
	{
		"name":"Украина",
		"currency":"UAH",
		"code":"UA",
		"cases":{
			"vi":"в Украину",
			"tv":"Украиной",
			"ro":"Украины",
			"pr":"Украине",
			"da":"Украине"
		},
		"name_translations":{
				"en":"Ukraine"
		}
	}
]
	
